server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shishuai2648/microservicecloud-config.git # GitHub上面的git仓库地址